// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_Do_List.Data;

#nullable disable

namespace To_Do_List.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("To_Do_List.Entities.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Habits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Exercise"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Journaling"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Planning"
                        });
                });

            modelBuilder.Entity("To_Do_List.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Urgent"
                        });
                });

            modelBuilder.Entity("To_Do_List.Entities.TaskHabit", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("HabitId")
                        .HasColumnType("int");

                    b.HasKey("TaskId", "HabitId");

                    b.HasIndex("HabitId");

                    b.ToTable("TaskHabits", (string)null);

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            HabitId = 1
                        },
                        new
                        {
                            TaskId = 2,
                            HabitId = 1
                        },
                        new
                        {
                            TaskId = 3,
                            HabitId = 2
                        },
                        new
                        {
                            TaskId = 4,
                            HabitId = 4
                        });
                });

            modelBuilder.Entity("To_Do_List.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete the project report by Friday.",
                            DueDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            IsDeleted = false,
                            Priority = "High",
                            Title = "Finish project report"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete this project by Friday.",
                            DueDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            IsDeleted = false,
                            Priority = "Medium",
                            Title = "Finish software project"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Read 20 pages of 'Atomic Habits'.",
                            DueDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            IsDeleted = false,
                            Priority = "Low",
                            Title = "Read Book"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Zoom call with product team.",
                            DueDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            IsDeleted = false,
                            Priority = "High",
                            Title = "Team Meeting"
                        });
                });

            modelBuilder.Entity("To_Do_List.Entities.TaskTag", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("TaskId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TaskTags", (string)null);

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            TagId = 1
                        },
                        new
                        {
                            TaskId = 1,
                            TagId = 4
                        },
                        new
                        {
                            TaskId = 2,
                            TagId = 2
                        },
                        new
                        {
                            TaskId = 3,
                            TagId = 3
                        },
                        new
                        {
                            TaskId = 4,
                            TagId = 1
                        },
                        new
                        {
                            TaskId = 4,
                            TagId = 4
                        });
                });

            modelBuilder.Entity("To_Do_List.Entities.TaskHabit", b =>
                {
                    b.HasOne("To_Do_List.Entities.Habit", "Habit")
                        .WithMany("TaskHabits")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("To_Do_List.Entities.TaskItem", "TaskItem")
                        .WithMany("TaskHabits")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("To_Do_List.Entities.TaskTag", b =>
                {
                    b.HasOne("To_Do_List.Entities.Tag", "Tag")
                        .WithMany("TaskTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("To_Do_List.Entities.TaskItem", "TaskItem")
                        .WithMany("TaskTags")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("To_Do_List.Entities.Habit", b =>
                {
                    b.Navigation("TaskHabits");
                });

            modelBuilder.Entity("To_Do_List.Entities.Tag", b =>
                {
                    b.Navigation("TaskTags");
                });

            modelBuilder.Entity("To_Do_List.Entities.TaskItem", b =>
                {
                    b.Navigation("TaskHabits");

                    b.Navigation("TaskTags");
                });
#pragma warning restore 612, 618
        }
    }
}
